version: '3.9'

services:
  workspace:
    container_name: ${PROJECT_NAME:-app2callgraph}-devcontainer
    build:
      context: .
      args:
        USERNAME: ${USERNAME:-dev}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    volumes:
      - ../:/home/workspace:cached
    ports:
      - 5555:5555